### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by SHWB** [caligin/netronner#7]
Could be possible showing rank achievements in an incremental fashion? I.e. not one achievement for each rank, but only the higher reached?

**Comment by caligin** [comment]
Doesn't really matter as long as it's perceived as such from the user. I believe implications+sequences is easier and more flexible for the implementation. I'll eventually change if this proves wrong. Anyway I'll make sure that the rank is perceived as a property on the interface.

**Comment by caligin** [comment]
https://github.com/caligin/netronner/commit/8edc86288e3bb328d5c159765a119d1283fba0eb introduces the concept of series. To complete the feature the remaining work is on the ui-side, I'm closing this ticket.
